#端口
server:
  port: 8070
#服务名称
spring:
  application:
    name: ApiGateway-zuul
  #consul的配置
  cloud:
    consul:
        host: localhost
        port: 8500
        discovery:
          serviceName: ApiGateway-zuul
#eureka:
#  client:
#    service-url:
#      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#      defaultZone: http://localhost:8888/eureka/




zuul:
  routes:
    #/api-a/路由
    api-a:
      path: /api-a/**
      serviceId: service-producer
    #/api-b/路由
    api-b:
      path: /api-b/**
      serviceId: service-producer
    #/github
    github:
      path: /github/**
      url: https://github.com/